[CmdletBinding()]
param(
    [switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$manifestPath = Join-Path $repositoryRoot "eng/interop/interop-manifest.json"
$outputPath = Join-Path $repositoryRoot "src/JYPPX.HipSharp/Generated/HipNativeMethods.g.cs"
$manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("// <auto-generated />")
$lines.Add("// Source: eng/interop/interop-manifest.json")
$lines.Add("")
$lines.Add("using System;")
$lines.Add("using System.Runtime.CompilerServices;")
$lines.Add("using System.Runtime.InteropServices;")
$lines.Add("using JYPPX.HipSharp.Memory;")
$lines.Add("using JYPPX.HipSharp.Rtc;")
$lines.Add("using JYPPX.HipSharp.Types;")
$lines.Add("")
$lines.Add("namespace JYPPX.HipSharp.Generated;")
$lines.Add("")
$lines.Add("/// <summary>")
$lines.Add("/// 提供由 manifest 生成的 HIP Runtime 与 HIPRTC C ABI 声明 / Provides manifest-generated HIP Runtime and HIPRTC C ABI declarations.")
$lines.Add("/// </summary>")
$lines.Add("internal static partial class HipNativeMethods")
$lines.Add("{")

foreach ($function in $manifest.functions) {
    $parameters = @($function.parameters | ForEach-Object { $_.declaration }) -join ", "
    $importName = switch ($function.library) {
        "amdhip64" { "HipNativeLibraryNames.RuntimeImportName" }
        "hiprtc" { "HipNativeLibraryNames.RtcImportName" }
        default { throw "Unsupported native library '$($function.library)' for $($function.entryPoint)." }
    }
    $lines.Add("    /// <summary>")
    $lines.Add("    /// $($function.summaryZh) / $($function.summaryEn).")
    $lines.Add("    /// </summary>")
    foreach ($parameter in $function.parameters) {
        $lines.Add("    /// <param name=`"$($parameter.name)`">方向：$($parameter.direction)，所有权：$($parameter.ownership) / Direction: $($parameter.direction); ownership: $($parameter.ownership).</param>")
    }
    $lines.Add("    /// <returns>原生返回值 / Native return value.</returns>")
    $lines.Add("#if NET7_0_OR_GREATER")
    $lines.Add("    [LibraryImport($importName, EntryPoint = `"$($function.entryPoint)`")]")
    $lines.Add("    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]")
    $lines.Add("    internal static partial $($function.returnType) $($function.managedName)($parameters);")
    $lines.Add("#else")
    $lines.Add("    [DllImport($importName, EntryPoint = `"$($function.entryPoint)`", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]")
    $lines.Add("    internal static extern $($function.returnType) $($function.managedName)($parameters);")
    $lines.Add("#endif")
    $lines.Add("")
}

$lines.Add("}")
$generated = ($lines -join "`n") + "`n"

if ($Verify) {
    if (-not (Test-Path -LiteralPath $outputPath -PathType Leaf)) {
        throw "Generated interop file is missing: $outputPath"
    }

    $current = [System.IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n")
    if ($current -ne $generated) {
        throw "Generated interop is stale. Run ./eng/generate-interop.ps1 and commit the result."
    }

    Write-Host "Generated interop verified against $manifestPath."
    return
}

[System.IO.File]::WriteAllText($outputPath, $generated, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated interop: $outputPath"
